#   __________________________     ____  _ _____________ _                       ______
#  /_  __/  _/ ____/ ____/ __ \   / __ \(_) __/ __/ ___/(_)___  ____ ____  _____/ / / /
#   / /  / // / __/ __/ / /_/ /  / / / / / /_/ /_ \__ \/ / __ \/ __ `/ _ \/ ___/ / / / 
#  / / _/ // /_/ / /___/ _, _/  / /_/ / / __/ __/___/ / / / / / /_/ /  __/ /  /_/_/_/  
# /_/ /___/\____/_____/_/ |_|  /_____/_/_/ /_/  /____/_/_/ /_/\__, /\___/_/  (_|_|_)   
#                                                            /____/                        
# v106

phonemes: dsacoustic/phonemes.json
languages: dsacoustic/languages.json
acoustic: dsacoustic/acoustic.onnx
dictionary: dsacoustic/dictionary.txt
vocoder: dsvocoder

hidden_size: 256

use_lang_id: true
use_key_shift_embed: true
use_speed_embed: true
use_energy_embed: false
use_breathiness_embed: false
use_voicing_embed: false
use_tension_embed: false
use_continuous_acceleration: true
use_variable_depth: true

max_depth: 0.6
sample_rate: 44100
hop_size: 512
win_size: 2048
fft_size: 2048
num_mel_bins: 128
mel_fmin: 40
mel_fmax: 16000
mel_base: e
mel_scale: slaney

speakers:
  - dsacoustic/tiger_fresh
  - dsacoustic/tiger_disco
  - dsacoustic/tiger_electric
  - dsacoustic/tiger_vinyl
  - dsacoustic/tiger_glam
  - dsacoustic/tiger_mystic
  - dsacoustic/tiger_royal

# for GEN & VEL
augmentation_args:
  random_pitch_shifting:
    range:
    - -5.0
    - 5.0
  random_time_stretching:
    range:
    - 0.5
    - 2.0